module: "mmcv"
variant: "standard" # 如果是特调版，可以写 "fix-headdim256"
upstream:
  repo: "https://github.com/open-mmlab/mmcv"
  branch: "v2.1.0"
  commit: "57c4e25"
env:
  python: "3.13"
  cuda: "13.0"
  pytorch: "2.11"
